spring.application.name=Festive-backend


# Busan ????? API  URL
festive.api.url=https://apis.data.go.kr/6260000/FestivalService/getFestivalKr?ServiceKey=%252FGSutEqLvnKnna6qTOlByvV2bKQ06qO7HJ%252F4FheQC5eNKClxKcJfY%252FWrDs89KedFWvF2eWzo%252FBr5uNAQ0%252FKgjQ%253D%253D&pageNo=1&numOfRows=10&resultType=resultType%3Djson